### ISSUE TITLE
Error mkdir

### ISSUE THREAD

**Issue by RikCost** [Epsylon42/mspfa-archive-helper#7]
I try this:
npm start -- --story 50130

![image](https://github.com/Epsylon42/mspfa-archive-helper/assets/69048938/07a14883-b40b-44f0-9830-27adefead46f)

downloading miscellaneous images
archive\assets\images\misc\YzAOR9X23DJlLPFG\gfkjdgdf.gif: file exists - skipping download
downloading css resources
$ fetch https://mspfa.com/css/?s=41577
archive\assets\cssres\mspfa.com\0.css: file exists - skipping download
archive\assets\cssres\mspfa.com\0.css is a css file - downloading recursively
archive\assets\cssres\file.garden\X1htvgJ0DEp_tp-Z\MSPFA_other\groupme\GoupmeHeart.png: file exists - skipping download
archive\assets\cssres\file.garden\X1htvgJ0DEp_tp-Z\MSPFA_other\groupme\GoupmeJoin.png: file exists - skipping download
archive\assets\cssres\file.garden\X1htvgJ0DEp_tp-Z\MSPFA_other\groupme\gorupme.png: file exists - skipping download
Error: ENOENT: no such file or directory, mkdir 'D:\mspfa-archive-helper\archive\assets\cssres\web.archive.org\web\20130116201541im_\http:\www.mspaforums.com\images\statusicon' - retrying 1
Error: ENOENT: no such file or directory, mkdir 'D:\mspfa-archive-helper\archive\assets\cssres\web.archive.org\web\20130116201541im_\http:\www.mspaforums.com\images\statusicon' - retrying 2
Error: ENOENT: no such file or directory, mkdir 'D:\mspfa-archive-helper\archive\assets\cssres\web.archive.org\web\20130116201541im_\http:\www.mspaforums.com\images\statusicon' - retrying 3
failed to download: Error: ENOENT: no such file or directory, mkdir 'D:\mspfa-archive-helper\archive\assets\cssres\web.archive.org\web\20130116201541im_\http:\www.mspaforums.com\images\statusicon'
download error limit (1) exceeded - stopping (consider using '--ignoreErrors' or '--stopAfterErrors <N>')

Syntaxis error in mkdir?

**Comment by Epsylon42** [comment]
Probably because of `:` in a file name. As far as I know, Windows does not allow that.
I can't really verify this, so I'll try using https://www.npmjs.com/package/path-sanitizer/v/2.0.0 and hope it works
